name: Cross-platform Build

on:
  push:
    branches: [ costumes ]
  pull_request:
    branches: [ costumes ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Build Demo
      run: |
        pip install conan
        conan install . --build=missing
        cmake --preset=conan-release
        cmake --build --preset=conan-release
